In [3]:
import pandas as pd
import numpy as np
from pandas.plotting import scatter_matrix
import matplotlib.pyplot as pyplot
from sklearn import preprocessing
pyplot.subplots_adjust(wspace=1, hspace=1)
red_wine = pd.read_csv("./Datasets/winequality-red.csv", sep=";")
red_wine.head()



fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

<Figure size 432x288 with 0 Axes>

In [74]:
X_train = np.array([[ 1., -1.,  2.],
                    [ 2.,  0.,  0.],
                    [ 0.,  1., -1.]])
X_test = np.array([[-2, 3, 0.5]])
min_max_scaler = preprocessing.MinMaxScaler()

standard_scaler = preprocessing.StandardScaler().fit(X_train)

In [75]:
min_max_scaler.fit_transform(X_train)
#MINMAXSCALER FIT AND TRANSFORM

array([[0.5       , 0.        , 1.        ],
       [1.        , 0.5       , 0.33333333],
       [0.        , 1.        , 0.        ]])

In [77]:
standard_scaler.transform(X_train)
#STANDARDSCALER TRANSFORM AFTER FIT

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [64]:
min_max_scaler.transform(X_test)
#TRANSFORM TEST DATA

array([[-1. ,  2. ,  0.5]])

In [66]:
scaler.transform(X_train)

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

array([0.        , 0.5       , 0.33333333])

array([0.81649658, 0.81649658, 1.24721913])